### ISSUE TITLE
v4. Runtime Exception after upgrading from v3.

### ISSUE THREAD

**Issue by ScottHutchinson** [elmish/Elmish.WPF#537]
After upgrading from Elmish.WPF v3.5.6 to v4.0.0-beta-45, I had to make some changes to the startup code to get it to build because the API changed.

You can see all the changes I made by comparing the elmishwpfv3 branch and the elmishwpfv4 branch. Ignore the main branch, which is not functional.

See changes at [https://github.com/ScottHutchinson/StructFilters/commit/56e40f1b42ad05b655d504afd0eda247a8277123#diff-c2cfa90a95d8f97f69a27c3501eb4a4fa5a355a6616312bc3c1570c5a42a92a2L358](https://github.com/ScottHutchinson/StructFilters/commit/56e40f1b42ad05b655d504afd0eda247a8277123#diff-c2cfa90a95d8f97f69a27c3501eb4a4fa5a355a6616312bc3c1570c5a42a92a2L358).

This is a minimal prototype of our complete application. It is a private repo. I have added @TysonMN and @LyndonGingerich  as contributors.

To reproduce the runtime exception, set the NG-DART project as the startup project. Running without debugging will show the exception with stack trace like below. The exception appears to occur during initialization of the `rootBindings`.
```
System.TypeInitializationException: The type initializer for '<StartupCode$NG-DART-StructFilters>.$NGDartStructFilters.StructFilters' threw an exception. ---> System.InvalidOperationException: The input list was empty.
   at Microsoft.FSharp.Collections.FSharpList`1.get_Head()
   at Domain.Model.get_IsEmpty() in C:\Users\hutchinsons\source\repos\StructFilters\NG-DART.StructFilters\Domain.fs:line 38
   at NGDartStructFilters.StructFilters.App.rootBindings@318.Invoke(Model m)
   at Elmish.WPF.BindingData.recursiveCase@230-4.Invoke(a x)
   at Elmish.WPF.BindingVmHelpers.Initialize.Recursive[model,msg](model initialModel, FSharpFunc`2 dispatch, FSharpFunc`2 getCurrentModel, BindingData`2 binding)
   at Elmish.WPF.DynamicViewModel`2..ctor(ViewModelArgs`2 args, FSharpList`1 bindings)
   at Elmish.WPF.ViewModel.designInstance[model,msg](model model, FSharpList`1 bindings)
   at <StartupCode$NG-DART-StructFilters>.$NGDartStructFilters.StructFilters..cctor() in C:\Users\hutchinsons\source\repos\StructFilters\NG-DART.StructFilters\StructFilters.fs:line 332
   --- End of inner exception stack trace ---
   at NGDartStructFilters.StructFilters.App.set_window(Window value)
   at NGDartStructFilters.StructFilters.PublicAPI.init(Window mainWindow, Window waitWindow) in C:\Users\hutchinsons\source\repos\StructFilters\NG-DART.StructFilters\StructFilters.fs:line 338
   at NGDartStructFilters.Views.App.Init()
   at CLR.LoadStructFiltersWindow(basic_string<char\,std::char_traits<char>\,std::allocator<char> >* , Void* structResource, Int32 structResourceLength, UInt16 msgTypeID, SByte* msgTypeName, SByte* parentStructName, Boolean* isSuccessful) in C:\Users\hutchinsons\source\repos\StructFilters\NG-DART.CLR\NG-DART.CLR.cpp:line 26
```

**Comment by ScottHutchinson** [comment]
I pushed [this possible fix](https://github.com/ScottHutchinson/StructFilters/commit/ac75238490c36caeecf7f3205d0ca13863f41e49) to the elmishwpfv4 branch. But after that, I am getting a different exception (see below). It really don't understand what is going wrong here.
```
System.TypeInitializationException: The type initializer for '<StartupCode$NG-DART-StructFilters>.$NGDartStructFilters.StructFilters' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=6.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at <StartupCode$NG-DART-StructFilters>.$NGDartStructFilters.StructFilters..cctor()
   --- End of inner exception stack trace ---
   at NGDartStructFilters.StructFilters.App.set_window(Window value)
   at NGDartStructFilters.StructFilters.PublicAPI.init(Window mainWindow, Window waitWindow) in C:\Users\scott\source\StructFilters\NG-DART.StructFilters\StructFilters.fs:line 338
   at NGDartStructFilters.Views.App.Init()
   at CLR.LoadStructFiltersWindow(basic_string<char\,std::char_traits<char>\,std::allocator<char> >* , Void* structResource, Int32 structResourceLength, UInt16 msgTypeID, SByte* msgTypeName, SByte* parentStructName, Boolean* isSuccessful) in C:\Users\scott\source\StructFilters\NG-DART.CLR\NG-DART.CLR.cpp:line 26
C:\Users\scott\source\StructFilters\x64\Debug\NG-DART.exe (process 14236) exited with code 0.
```

**Comment by ScottHutchinson** [comment]
I seem to have this working now on the elmishwpfv4 branch. [Modifying the binding redirect for FSharp.Core](https://github.com/ScottHutchinson/StructFilters/commit/e817c029de1638d52755d7bee47b4b2d7fc8b565) fixed the last problem. Now I can proceed with work on issue #527.

**Comment by ScottHutchinson** [comment]
> System.TypeInitializationException: The type initializer for '<StartupCode$NG-DART-StructFilters>.$NGDartStructFilters.StructFilters' threw an exception. ---> System.InvalidOperationException: The input list was empty.
>    at Microsoft.FSharp.Collections.FSharpList`1.get_Head()
>    at Domain.Model.get_IsEmpty() in C:\Users\hutchinsons\source\repos\StructFilters\NG-DART.StructFilters\Domain.fs:line 38
>    at NGDartStructFilters.StructFilters.App.rootBindings@318.Invoke(Model m)
>    at Elmish.WPF.BindingData.recursiveCase@230-4.Invoke(a x)

@TysonMN , Note that this does appear to demonstrate a change in behavior in the `BindingData` module or possibly in the `RoseTree` in v4 vs. v3. In v4, the `RoseTree` returned by the `rootBindings` had no children where in v3 it had at least one child. As far as I know, this is not due to any changes in my application; although I might be overlooking something. Or it might be a rare corner case not worth fixing.

**Comment by TysonMN** [comment]
Glad you were able to solve your problem
